modLoader="javafml"
loaderVersion="[4,)"
license="MIT"

[[mods]]
modId="fuckcrafter"
version="1.0.0"
displayName="FuckCrafter"
description="Allows extracting items from Mechanical Crafter"
authors="YourName"

[[dependencies.fuckcrafter]]
modId="neoforge"
type="required"
versionRange="[21.1,22)"
ordering="NONE"
side="BOTH"

[[dependencies.fuckcrafter]]
modId="minecraft"
type="required"
versionRange="[1.21.1,1.22)"
ordering="NONE"
side="BOTH"

[[dependencies.fuckcrafter]]
modId="create"
type="required"
versionRange="[0.6.0,)"
ordering="AFTER"
side="BOTH"

[[mixins]]
config="fuckcrafter.mixins.json"
